name: Test

on: [push, pull_request]

jobs:
  mocha:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
       with:
         node-version: 16
     - run: yarn
     - run: yarn test
     - uses: codecov/codecov-action@v2
